version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: trello_postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: trello_database
    volumes:
      - postgres_trello_data:/var/lib/postgresql/data

volumes:
  postgres_trello_data: {}
